// build.mjs -- fold the whole game into one HTML file that runs from file://
// (ES modules cannot be loaded over file://, so the modules are wrapped in a
// tiny registry instead of being imported).
//
//   node tools/build.mjs   ->   dist/RULE-BREAK.html

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(ROOT, p), 'utf8');

// Dependency order. Every module only imports ones listed before it.
const MODULES = [
  'src/expr.js',
  'src/sentence.js',
  'src/pixel.js',
  'src/engine.js',
  'src/render.js',
  'src/audio.js',
  'src/save.js',
  'src/stages/l1.js',
  'src/stages/l2.js',
  'src/stages/l3.js',
  'src/stages/l4.js',
  'src/stages/l5.js',
  'src/stages/l6.js',
  'src/stages/l7.js',
  'src/stages/index.js',
  'src/app.js',
];

const keyOf = (path) => path.replace(/^src\//, '').replace(/\.js$/, '');

function transform(path, code) {
  const exports = new Set();
  const dir = path.replace(/\/[^/]*$/, '');   // e.g. "src/stages"

  // import { a, b as c } from './x.js';  ->  const { a, b: c } = __M['x'];
  code = code.replace(/^import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?\s*$/gm, (_, names, from) => {
    const target = new URL(from, 'file:///' + dir + '/').pathname.replace(/^\/+/, '');
    const clean = names.split(',').map((n) => n.trim()).filter(Boolean)
      .map((n) => n.replace(/\s+as\s+/, ': '))
      .join(', ');
    return `const { ${clean} } = __M['${keyOf(target)}'];`;
  });

  // collect and strip export markers
  code = code.replace(/^export\s+(async\s+)?(function|class)\s+(\w+)/gm, (m, a, kind, name) => {
    exports.add(name);
    return `${a || ''}${kind} ${name}`;
  });
  code = code.replace(/^export\s+(const|let|var)\s+([^=;]+)=/gm, (m, kind, decls) => {
    // handles "const A = ..." and "const A = 1, B = 2" declarations alike
    for (const part of (decls + '=').split(',')) {
      const n = part.trim().split(/[\s=]/)[0];
      if (n) exports.add(n);
    }
    return `${kind} ${decls}=`;
  });
  // "export const GLYPH_W = 5, GLYPH_H = 7;" leaves a second name on the same line
  const multi = code.match(/^(const|let|var)\s+\w+\s*=\s*[^;]*,\s*(\w+)\s*=/gm) || [];
  for (const m of multi) {
    const n = m.match(/,\s*(\w+)\s*=/);
    if (n) exports.add(n[1]);
  }

  return { code, exports: [...exports] };
}

function bundleOf(modules) {
  let out = `// RULE//BREAK -- single file build. Generated by tools/build.mjs.\n`
    + `const __M = {};\n`;
  for (const path of modules) {
    const { code, exports } = transform(path, read(path));
    out += `\n// ===== ${path} =====\n`
      + `__M['${keyOf(path)}'] = (function () {\n${code}\nreturn { ${exports.join(', ')} };\n})();\n`;
  }
  return out;
}

const css = read('style.css');

function page(htmlFile, modules, extraHead = '') {
  const html = read(htmlFile);
  const body = html
    .replace(/<link rel="stylesheet"[^>]*>/, '')
    .replace(/<script type="module"[^>]*><\/script>/, '')
    .match(/<body>([\s\S]*)<\/body>/)[1];
  const inlineStyle = (html.match(/<style>([\s\S]*?)<\/style>/) || [, ''])[1];
  return { body, inlineStyle, js: bundleOf(modules) };
}

const game = page('index.html', MODULES);
const bundle = game.js;
const body = game.body;

const out = `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">
<meta name="theme-color" content="#050505">
<meta name="apple-mobile-web-app-capable" content="yes">
<title>RULE//BREAK</title>
<style>
${css}
</style>
</head>
<body>
${body}
<script>
${bundle}
</script>
</body>
</html>
`;

mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(join(ROOT, 'dist', 'RULE-BREAK.html'), out);
console.log('dist/RULE-BREAK.html         ' + Math.round(out.length / 1024) + ' KB');

// --- the stage editor, same treatment -------------------------------------
const ED_MODULES = MODULES.filter((m) => m !== 'src/app.js').concat('src/editor.js');
const ed = page('editor.html', ED_MODULES);
const edOut = `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RULE//BREAK - STAGE EDITOR</title>
<style>
${css}
${ed.inlineStyle}
</style>
</head>
<body>
${ed.body.replace('href="index.html"', 'href="RULE-BREAK.html"')}
<script>
${ed.js}
</script>
</body>
</html>
`;
writeFileSync(join(ROOT, 'dist', 'RULE-BREAK-EDITOR.html'), edOut);
console.log('dist/RULE-BREAK-EDITOR.html  ' + Math.round(edOut.length / 1024) + ' KB');
