// LEVEL 1 -- the world looks ordinary. It is not.
// Nothing here is ever explained; every law has physical evidence on the board.

export const L1 = [
{
  id: '1', level: 1, title: 'FIRST STEP',
  grid: { rows: ['#######', '#.....#', '#.....#', '#.....#', '#.....#', '#.....#', '#######'] },
  objects: [{ kind: 'player', x: 1, y: 3 }, { kind: 'goal', x: 5, y: 3 }],
  available_ui_actions: ['undo', 'reset'],
  hint_1: '歩けばいい。',
  hint_2: '右へ。',
  hint_3: '右へ4回。これはチュートリアルだ。……たぶん。',
  solution: ['R', 'R', 'R', 'R'],
},
{
  id: '2', level: 1, title: 'TEN',
  grid: { rows: ['#######', '#.....#', '#.....#', '#yyyyy#', '#y###y#', '#y###y#', '#######'],
    legend: { y: { type: 'yellowfloor' } } },
  objects: [{ kind: 'player', x: 1, y: 5 }, { kind: 'goal', x: 5, y: 5 }],
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { v: 'turn' }, b: 10 }],
  marks: [{ x: 3, y: 3, g: '10' }],
  available_ui_actions: ['undo', 'reset'],
  laws: [{ id: 'L2', name: 'ゴールは10手目に踏んだときだけゴールになる', answer: ['ゴール', '10', '手目'] }],
  tokens: ['ゴール', '壁', '10', '3', '手目', '偶数', '奇数', '右', '接触', '反転'],
  hint_1: '盤面ではなく、盤面の外の数字を見よう。',
  hint_2: 'MOVES は何のために表示されている？',
  hint_3: '黄色い床の道は何歩ある？ その歩数ちょうどでゴールを踏め。',
  solution: ['U', 'U', 'U', 'R', 'R', 'R', 'R', 'D', 'D', 'D'],
},
{
  id: '3', level: 1, title: 'TRACE',
  grid: { rows: ['#######', '#..#..#', '#..#..#', '#.....#', '#..#..#', '#..#..#', '#######'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'key', keyId: 'a', x: 5, y: 1 },
    { kind: 'key', keyId: 'b', x: 1, y: 5 },
    { kind: 'goal', x: 5, y: 5 },
  ],
  hidden_rules: [{
    id: 'R_TRACE', name: '同じマスを2回踏むと、そのマスは壁になる', when: 'afterMove',
    if: { op: 'and', args: [{ v: 'arg.moved' }, { op: '>=', a: { v: 'visitsPrev' }, b: 2 }] },
    then: [{ do: 'setTilePrev', to: 'wall' }, { do: 'sound', name: 'thud' }],
    note: '通った床をもう一度通った → 背後で音がした',
    answer: ['床', '2', '回', '壁'],
  }],
  win_conditions: [{ at: ['player', 'goal'] }, { v: 'key.a' }, { v: 'key.b' }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['床', '壁', '2', '3', '回', '踏む', '消える', '鍵', '偶数', '反転'],
  hint_1: '道が減っていないか？',
  hint_2: '一度通った道を、もう一度通ってみて、そのあと振り返れ。',
  hint_3: '2回踏んだ床は失われる。どちらの鍵を先に取るかが全て。',
  solution: ['D', 'D', 'D', 'D', 'U', 'U', 'R', 'R', 'R', 'R', 'U', 'U', 'D', 'D', 'D', 'D'],
},
{
  id: '4', level: 1, title: 'RIGHT RIGHT RIGHT',
  grid: { rows: ['#######', '#.....#', '#.....#', '#.....#', '#.....#', '#.....#', '#######'] },
  objects: [{ kind: 'player', x: 1, y: 5 }, { kind: 'goal', x: 5, y: 1 }],
  flags: { gravDir: 'down' },
  marks: [{ x: 1, y: 5, g: '>' }, { x: 2, y: 5, g: '>' }, { x: 3, y: 5, g: '>' }],
  hidden_rules: [{
    id: 'R_GRAV', name: '3回右へ進むと重力が反転する', when: 'afterMove',
    if: { op: '==', a: { v: 'streak.right' }, b: 3 },
    then: [{ do: 'flipGravity' }, { do: 'sound', name: 'low' }, { do: 'flash', text: '' }],
    note: '右へ3回 → 世界が裏返った',
    answer: ['右', '3', '回', '重力', '反転'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['右', '左', '3', '2', '回', '重力', '反転', '床', '壁', '手目'],
  hint_1: '上には行けない。跳べないのだから。',
  hint_2: '床に描かれた矢印は何本ある？',
  hint_3: '同じ方向へ連続して進んだ回数を数えよう。3回目に何かが起きる。',
  solution: ['R', 'R', 'R', 'R'],
},
{
  id: '5', level: 1, title: 'PUSH',
  grid: { rows: ['#########', '#.......#', '#.###.#.#', '#.#...#.#', '#.#####.#', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 2, y: 1 },
    { kind: 'goal', x: 3, y: 3 },
    { id: 'bx1', kind: 'box', x: 1, y: 1, push: false },
    { id: 'bx2', kind: 'box', x: 7, y: 2, push: false },
    { id: 'bx3', kind: 'box', x: 5, y: 2, push: false },
  ],
  hidden_rules: [{
    id: 'R_PUSHGOAL', name: '箱を押すと、箱ではなくゴールが反対方向へ動く', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.by' }, b: 'box' },
    then: [{ do: 'moveObj', ref: 'goal', dir: 'opposite', by: 1, force: 'objects' }, { do: 'sound', name: 'blip' }],
    note: '箱を押した → 箱は動かず、別の何かが動いた',
    answer: ['箱', 'ゴール', '反対', '動く'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', 'ゴール', '壁', '反対', '同じ', '動く', '押す', '2', '回', '重力'],
  hint_1: '箱はびくともしない。だが「何も起きていない」わけではない。',
  hint_2: '箱を押したとき、盤面のどこかを見張っていよう。',
  hint_3: 'ゴールは押した向きと逆へ動く。ゴールを、自分が行ける場所まで運べ。',
  solution: ['L', 'L', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'L', 'L'],
},
{
  id: '6', level: 1, title: 'FACE',
  grid: { rows: ['#########', '#.......#', '####r####', '#.......#', '#########'],
    legend: { r: { type: 'redwall', solid: { op: '!=', a: { v: 'facing' }, b: 'up' } } } },
  objects: [{ kind: 'player', x: 1, y: 3 }, { kind: 'goal', x: 7, y: 1 }],
  marks: [{ x: 4, y: 3, g: '^' }],
  hidden_rules: [{
    id: 'R_FACE', name: '上を向いている間だけ赤い壁を通過できる', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.tile' }, b: 'redwall' },
    then: [{ do: 'sound', name: 'err' }],
    note: '赤い壁に阻まれた → そのときの向きは？',
    answer: ['赤', '壁', '上', '向き', '通過'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['赤', '青', '壁', '上', '下', '向き', '通過', '偶数', '手目', '箱'],
  hint_1: 'その赤いものは、本当に壁か？',
  hint_2: 'プレイヤーの目はどこを向いている？',
  hint_3: '床の矢印の上に立って、その向きへ進め。赤は上を向いた者だけを通す。',
  solution: ['R', 'R', 'R', 'U', 'U', 'R', 'R', 'R'],
},
{
  id: '7', level: 1, title: 'PHASE',
  grid: { rows: ['#########', '#....g..#', '#.#####.#', '#...#...#', '#########'],
    legend: { g: { type: 'glass' } } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  turn_conditions: { countBlocked: true },
  marks: [{ x: 1, y: 1, g: '.' }, { x: 3, y: 1, g: '.' }, { x: 5, y: 1, g: '.' }, { x: 7, y: 1, g: '.' },
    { x: 2, y: 3, g: '.' }, { x: 6, y: 3, g: '.' }],
  hidden_rules: [{
    id: 'R_PHASE', name: '奇数手では壁が存在し、偶数手では床になる', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.tile' }, b: 'glass' },
    then: [{ do: 'sound', name: 'err' }],
    note: '透明な壁に阻まれた → そのときの手数は奇数だった',
    answer: ['壁', '奇数', '偶数', '手目', '存在'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['壁', '床', '奇数', '偶数', '手目', '存在', '色', '向き', '3', '回'],
  hint_1: '行ったり来たりしても、何も変わらない。それ自体が答えの半分だ。',
  hint_2: 'MOVES は、進めなかったときも増える。',
  hint_3: 'この盤面では手数の偶奇と自分の位置の色が連動している。壁に頭をぶつけて、その連動を切れ。',
  solution: ['U', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '8', level: 1, title: 'ODD',
  grid: { rows: ['#########', '#.......#', '#.......#', '#.......#', '#########'] },
  objects: [{ kind: 'player', x: 1, y: 2 }, { kind: 'goal', x: 7, y: 2 }],
  turn_conditions: { countBlocked: true },
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { op: '%', a: { v: 'turn' }, b: 2 }, b: 1 }],
  laws: [{ id: 'L8', name: 'ゴールは奇数手のときだけ有効', answer: ['ゴール', '奇数', '手目'] }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ゴール', '奇数', '偶数', '手目', '10', '壁', '向き', '重力', '接触', '存在'],
  hint_1: 'ゴールの上に立っている。それでも駄目なら、足りないのはゴールではない。',
  hint_2: 'ステージ名を声に出して読め。',
  hint_3: '前ステージで学んだはずだ。壁を殴っても1手は進む。ゴールの上で1手潰せ。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '9', level: 1, title: 'STOPPER',
  grid: { rows: ['#########', '#.#.....#', '#.#.....#', '#.......#', '#.......#', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { id: 'slider', kind: 'box', x: 2, y: 3, slide: true },
    { kind: 'switch', link: 'a', x: 5, y: 3 },
    { kind: 'door', link: 'a', x: 1, y: 2 },
    { kind: 'goal', x: 1, y: 1 },
  ],
  hidden_rules: [{
    id: 'R_TRACE9', name: '同じマスを2回踏むと、そのマスは壁になる', when: 'afterMove',
    if: { op: 'and', args: [{ v: 'arg.moved' }, { op: '>=', a: { v: 'visitsPrev' }, b: 2 }] },
    then: [{ do: 'setTilePrev', to: 'wall' }, { do: 'sound', name: 'thud' }],
    note: '2度踏んだ床を離れた → 背後が閉じた',
    answer: ['床', '2', '回', '壁'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['床', '壁', '箱', '2', '回', '止まる', '滑る', 'スイッチ', '奇数', '重力'],
  hint_1: 'その箱は、押されると止まらない。ならば「止める物」を用意すればいい。',
  hint_2: '壁は最初から置いてある物とは限らない。3ステージ前を思い出せ。',
  hint_3: '自分の足で壁を作る。箱が止まってほしいマスの、ひとつ先に作れ。',
  solution: ['D', 'R', 'R', 'R', 'R', 'R', 'U', 'D', 'U', 'L', 'D', 'L', 'L', 'L', 'L', 'U', 'R', 'L', 'U', 'U'],
},
];
