// LEVEL 2 -- the laws stop being obstacles and start being tools.
// Every stage here is unsolvable unless a discovered rule is deliberately abused.

export const L2 = [
{
  id: '10', level: 2, title: 'SWAP',
  grid: { rows: ['#########', '#.....#.#', '#.....#.#', '#.....=.#', '#.....#.#', '#.....#.#', '#########'],
    legend: { '=': { type: 'grate', solid: true, boxPass: true } } },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { id: 'bx', kind: 'box', x: 2, y: 3 },
    { kind: 'goal', x: 7, y: 1 },
  ],
  marks: [{ x: 2, y: 5, g: '4' }],
  hidden_rules: [{
    id: 'R_SWAP', name: '箱を4回押すと、箱とプレイヤーの位置が入れ替わる', when: 'onPush',
    if: { op: '==', a: { objProp: ['box', 'pushed'] }, b: 4 },
    then: [{ do: 'swap', a: 'player', b: 'box' }, { do: 'sound', name: 'warp' }, { do: 'flash', text: '' }],
    note: '4回目の押し込み → 自分の居場所が変わった',
    answer: ['箱', '4', '回', '入れ替わる'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '4', '3', '回', '入れ替わる', '押す', '壁', '格子', '重力', 'ゴール'],
  hint_1: '格子は壁ではない。ただしお前は通れない。',
  hint_2: '押した回数を数えろ。床に数字が書いてある。',
  hint_3: '4回目の押しで箱と自分が入れ替わる。入れ替わりたい場所へ、先に箱を送り込め。',
  solution: ['R', 'R', 'R', 'R', 'R', 'U', 'U'],
},
{
  id: '11', level: 2, title: 'CAGE',
  grid: { rows: ['#########', '#.......#', '####.####', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { kind: 'enemy', x: 6, y: 1, behavior: 'patrol', patrol: ['left', 'right'] },
    { kind: 'goal', x: 7, y: 1 },
  ],
  hidden_rules: [{
    id: 'R_TRACE11', name: '同じマスを2回踏むと、そのマスは壁になる', when: 'afterMove',
    if: { op: 'and', args: [{ v: 'arg.moved' }, { op: '>=', a: { v: 'visitsPrev' }, b: 2 }] },
    then: [{ do: 'setTilePrev', to: 'wall' }, { do: 'sound', name: 'thud' }],
    note: '2度踏んだ床を離れた → 背後が閉じた',
    answer: ['床', '2', '回', '壁'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['床', '壁', '2', '回', '敵', '通れない', '閉じ込める', '奇数', '重力', '箱'],
  hint_1: '敵は、お前が作った壁も通れない。',
  hint_2: '敵はお前が動いたときだけ動く。止まっていても、時間は進まない。',
  hint_3: '自分の足跡で通路を切断し、敵を反対側へ置き去りにしろ。切る位置と、切る瞬間に自分がどちら側にいるかが全て。',
  solution: ['R', 'R', 'R', 'U', 'U', 'R', 'L', 'R', 'R', 'R'],
},
{
  id: '12', level: 2, title: 'QUIET ROOM',
  grid: { rows: ['#######', '#.....#', '#.###.#', '#.....#', '#.###.#', '#.....#', '#######'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'goal', x: 1, y: 5 },
    { id: 's12box', kind: 'box', x: 3, y: 3, spawnIf: { global: 's40_seen' } },
    { kind: 'switch', link: 'p', x: 5, y: 3, spawnIf: { global: 's40_seen' } },
  ],
  hidden_rules: [{
    id: 'R_S12', name: 'この部屋で起きたことは、この部屋だけの話ではない', when: 'everyTurn',
    if: { op: 'and', args: [{ countObj: 'box' }, { at: ['box', 'switch'] }] },
    then: [{ do: 'setGlobal', key: 's12_box_placed', value: true },
      { do: 'flash', text: 'SOMEWHERE ELSE' }, { do: 'sound', name: 'discover' }],
    note: '箱が台座に載った → 別の場所で音がした',
    answer: ['箱', '台座', '別', 'ステージ'],
  }],
  cross_stage_variables: { read: ['s40_seen'], write: ['s12_box_placed'] },
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '台座', '別', 'ステージ', '影響', '壁', '2', '回', '重力', '手目'],
  hint_1: 'ここは静かだ。何もない。……本当に、最初から何もなかったか？',
  hint_2: 'このステージに来た回数を思い出せ。以前と違うものが置かれていないか。',
  hint_3: '箱を台座へ押し込め。効果はこのステージには現れない。',
  solution: ['D', 'D', 'D', 'D'],
  solution_after: ['D', 'D', 'R', 'R', 'R', 'L', 'L', 'L', 'D', 'D'],
},
{
  id: '13', level: 2, title: 'THROUGH',
  grid: { rows: ['#########', '#.......#', '#.#####.#', '#.#...#.#', '#.#####.#', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'goal', x: 3, y: 3 },
    { id: 'anchor', kind: 'box', x: 7, y: 1, push: false },
  ],
  hidden_rules: [{
    id: 'R_GHOSTGOAL', name: 'ゴールは物体ではないので、壁をすり抜ける', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.by' }, b: 'box' },
    then: [{ do: 'moveObj', ref: 'goal', dir: 'opposite', by: 1, force: true }, { do: 'sound', name: 'blip' }],
    note: 'ゴールが壁の中へ入っていった',
    answer: ['ゴール', '壁', 'すり抜ける', '反対'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ゴール', '壁', 'すり抜ける', '反対', '箱', '物体', '2', '回', '重力', '手目'],
  hint_1: 'その部屋には入口がない。だから入口を探すのは間違いだ。',
  hint_2: '前に箱を押したとき、ゴールはどう動いた？ 今回は何が違う？',
  hint_3: 'ゴールを壁の外まで歩かせろ。ゴールに壁は関係ない。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L', 'L', 'D', 'D'],
},
{
  id: '14', level: 2, title: 'CEILING',
  grid: { rows: ['#########', '#.......#', '#######.#', '#.......#', '#.#######', '#.......#', '#########'] },
  objects: [{ kind: 'player', x: 1, y: 5 }, { kind: 'goal', x: 1, y: 1 }],
  flags: { gravDir: 'down' },
  marks: [{ x: 1, y: 5, g: '>' }, { x: 2, y: 5, g: '>' }, { x: 3, y: 5, g: '>' }],
  hidden_rules: [{
    id: 'R_GRAV14', name: '3回右へ進むと重力が反転する', when: 'afterMove',
    if: { op: '==', a: { v: 'streak.right' }, b: 3 },
    then: [{ do: 'flipGravity' }, { do: 'sound', name: 'low' }, { do: 'flash', text: '' }],
    note: '右へ3回 → 世界が裏返った',
    answer: ['右', '3', '回', '重力', '反転'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['右', '3', '回', '重力', '反転', '連続', '壁', '床', '手目', '箱'],
  hint_1: '落ちる方向は、ひとつではない。',
  hint_2: '反転する条件を、望まないときに満たしていないか？',
  hint_3: '右へ3回連続で進むと反転する。ならば「連続」を切ればいい。2歩進んで1歩戻れ。',
  solution: ['R', 'R', 'R', 'L', 'L', 'L',
    'R', 'R', 'L', 'R', 'R', 'L', 'R', 'R', 'L', 'R', 'R', 'L', 'R', 'R',
    'L', 'L', 'L', 'L', 'L', 'L'],
},
{
  id: '15', level: 2, title: 'SHIFT',
  grid: { rows: ['#########', '#.......#', '#.......#', '#....g..#', '#########'],
    legend: { g: { type: 'glass' } } },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { id: 'bx', kind: 'box', x: 2, y: 1 },
    { kind: 'goal', x: 7, y: 3 },
  ],
  hidden_rules: [{
    id: 'R_PUSHTURN', name: '箱を押すとターン数が+2される', when: 'onPush',
    if: true,
    then: [{ do: 'addTurn', by: 1 }, { do: 'sound', name: 'blip' }],
    note: '箱を押した → MOVES が2つ進んだ',
    answer: ['箱', '押す', '手数', '増える'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '押す', '手数', '増える', '奇数', '偶数', '壁', '存在', '色', '重力'],
  hint_1: '透明な壁の法則は7面と同じだ。ならば同じ手が使える……とは限らない。',
  hint_2: 'ここには壁を殴っても手数が増えない。増やす方法は他にある。',
  hint_3: '箱を1回押すたび、手数が余分に1つ進む。それで偶奇をずらせ。',
  solution: ['U', 'U', 'R', 'D', 'D', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '16', level: 2, title: 'FILL',
  grid: { rows: ['#########', '#.......#', '#.......#', '#ooooooo#', '#####.###', '#.......#', '#########'],
    legend: { o: { type: 'hole' } } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { id: 'bx', kind: 'box', x: 2, y: 2 },
    { kind: 'goal', x: 7, y: 5 },
  ],
  hidden_rules: [{
    id: 'R_FILL', name: '穴に落ちた箱は床になる', when: 'everyTurn',
    if: { op: '==', a: { tileAt: [{ objProp: ['box', 'x'] }, { objProp: ['box', 'y'] }] }, b: 'hole' },
    then: [
      { do: 'setTile', x: { objProp: ['box', 'x'] }, y: { objProp: ['box', 'y'] }, to: 'floor' },
      { do: 'remove', ref: 'box' }, { do: 'sound', name: 'thud' }, { do: 'flash', text: '' }],
    note: '箱が穴へ落ちた → 穴が消えた',
    answer: ['箱', '穴', '床', '落ちる'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '穴', '床', '落ちる', '壁', '2', '回', '重力', '手数', '入れ替わる'],
  hint_1: '穴は渡れない。だが穴は、埋まらないとは言っていない。',
  hint_2: '箱は1つしかない。落とす場所を間違えると詰む。',
  hint_3: '下の部屋への入口は1箇所しかない。その真上の穴を埋めろ。',
  solution: ['D', 'R', 'R', 'R', 'U', 'R', 'D', 'D', 'D', 'D', 'R', 'R'],
},
];
