// LEVEL 3 -- two to four laws per stage. Knowing each one is not enough;
// they have to be played against each other.

const RED_EVEN = (id) => ({
  id, name: '赤い壁は偶数ターンにだけ通れる', when: 'moveBlocked',
  if: { op: '==', a: { v: 'arg.tile' }, b: 'redwall' },
  then: [{ do: 'sound', name: 'err' }],
  note: '赤い壁に阻まれた → そのときの手数は？',
  answer: ['赤', '壁', '偶数', '手目'],
});

const BLUE_FLIP = (id) => ({
  id, name: '青い床を踏むと奇数と偶数の定義が逆転する', when: 'onEnter',
  if: { op: '==', a: { v: 'arg.tile' }, b: 'bluefloor' },
  then: [{ do: 'toggleFlag', flag: 'parityFlip' }, { do: 'sound', name: 'low' }, { do: 'flash', text: '' }],
  note: '青い床を踏んだ → 何かの定義が入れ替わった',
  answer: ['青', '床', '偶数', '奇数', '反転'],
});

const PUSH_TURN = (id) => ({
  id, name: '箱を押すとターン数が+2される', when: 'onPush', if: true,
  then: [{ do: 'addTurn', by: 1 }, { do: 'sound', name: 'blip' }],
  note: '箱を押した → MOVES が2つ進んだ',
  answer: ['箱', '押す', '手数', '増える'],
});

const RED = { type: 'redwall', solid: { op: '==', a: { v: 'parity' }, b: 1 } };
const BLUEW = { type: 'bluewall', solid: { op: '==', a: { v: 'parity' }, b: 0 } };
const BLUEF = { type: 'bluefloor' };

export const L3 = [
{
  id: '17', level: 3, title: 'CROSS',
  grid: { rows: ['#########', '#....r..#', '#.#######', '#b......#', '#########'],
    legend: { r: RED, b: BLUEF } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  hidden_rules: [RED_EVEN('R_RED'), BLUE_FLIP('R_BLUE')],
  rule_priority: ['R_BLUE', 'R_RED'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['赤', '青', '壁', '床', '偶数', '奇数', '手目', '反転', '定義', '重力'],
  hint_1: '赤い壁の法則は7面の透明な壁とよく似ている。だが今回は殴っても手数が増えない。',
  hint_2: '盤面には、まだ意味の分かっていない色がもう一つある。',
  hint_3: '青い床を踏んでから、赤い壁の前に立て。偶奇の意味そのものが入れ替わる。',
  solution: ['D', 'D', 'U', 'U', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '18', level: 3, title: 'TWICE',
  grid: { rows: ['#########', '#..b....#', '####r####', '#..b....#', '#####r###', '#.......#', '#########'],
    legend: { r: RED, b: BLUEF } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 5 }],
  hidden_rules: [RED_EVEN('R_RED'), BLUE_FLIP('R_BLUE')],
  rule_priority: ['R_BLUE', 'R_RED'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['赤', '青', '壁', '床', '偶数', '奇数', '反転', '2', '回', '手目'],
  hint_1: '青い床は2枚ある。2枚とも踏む必要があるとは限らないし、1枚で足りるとも限らない。',
  hint_2: '1枚目の門を抜けた時点で、偶奇の意味は入れ替わったままだ。',
  hint_3: '門ごとに必要な偶奇が違う。青い床は何度でも踏める。',
  solution: ['R', 'R', 'R', 'D', 'D', 'L', 'R', 'R', 'D', 'D', 'R', 'R'],
},
{
  id: '19', level: 3, title: 'CHAIN',
  grid: { rows: ['##########', '#....b...#', '######r###', '#........#', '##########'],
    legend: { r: RED, b: BLUEF } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { id: 'bx', kind: 'box', x: 5, y: 1 },
    { kind: 'goal', x: 8, y: 3 },
  ],
  hidden_rules: [RED_EVEN('R_RED'), BLUE_FLIP('R_BLUE'), PUSH_TURN('R_PUSH')],
  rule_priority: ['R_PUSH', 'R_BLUE', 'R_RED'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['赤', '青', '箱', '壁', '床', '偶数', '奇数', '反転', '手数', '増える'],
  hint_1: '3つの法則が同時に効いている。1つずつ確かめろ。',
  hint_2: '箱は青い床の上に乗っている。どければ何が踏める？',
  hint_3: '箱を押すと手数は+2される。偶奇は変わらない。偶奇を変えるのは青い床のほうだ。',
  solution: ['R', 'R', 'R', 'R', 'R', 'D', 'D', 'R', 'R'],
},
{
  id: '20', level: 3, title: 'PHASES',
  grid: { rows: ['#########', '#...r.G.#', '#.b.....#', '#.......#', '#########'],
    legend: { r: RED, G: BLUEW, b: BLUEF } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  turn_conditions: { countBlocked: true },
  hidden_rules: [RED_EVEN('R_RED'), BLUE_FLIP('R_BLUE'), {
    id: 'R_BLUEW', name: '青い壁は赤い壁と逆の位相を持つ', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.tile' }, b: 'bluewall' },
    then: [{ do: 'sound', name: 'err' }],
    note: '青い壁に阻まれた → 赤とは逆の条件らしい',
    answer: ['青', '壁', '奇数', '手目'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['赤', '青', '壁', '偶数', '奇数', '逆', '手目', '床', '反転', '重力'],
  hint_1: '2つの門は、同時に開かない。',
  hint_2: '片方を抜けた直後、もう片方は必ず閉じている。',
  hint_3: '門と門の間で1手だけ無駄にしろ。壁を殴れば手数は進む。',
  solution: ['R', 'R', 'R', 'R', 'U', 'R', 'R'],
},
{
  id: '21', level: 3, title: 'ORDER',
  grid: { rows: ['#########', '#.y...G.#', '#.......#', '#.....y.#', '#########'],
    legend: { y: { type: 'yellowfloor' }, G: { type: 'gate', solid: { op: 'not', a: { v: 'flag.gate' } } } } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  turn_conditions: { countBlocked: true },
  hidden_rules: [
    { id: 'R_ADD', name: '黄色い床はターン数を+1する', when: 'onEnter',
      if: { op: '==', a: { v: 'arg.tile' }, b: 'yellowfloor' },
      then: [{ do: 'addTurn', by: 1 }, { do: 'sound', name: 'blip' }],
      note: '黄色い床 → MOVES が余分に進んだ',
      answer: ['黄', '床', '手数', '増える'] },
    { id: 'R_GATE', name: '黄色い床を踏んだ瞬間の手数が奇数なら門が開く', when: 'onEnter',
      if: { op: '==', a: { v: 'arg.tile' }, b: 'yellowfloor' },
      then: [{ do: 'setFlag', flag: 'gate', value: { op: '==', a: { op: '%', a: { v: 'turn' }, b: 2 }, b: 1 } },
        { do: 'sound', name: 'low' }],
      note: '黄色い床 → 遠くの門の音が変わった',
      answer: ['黄', '床', '奇数', '門', '開く'] },
  ],
  rule_priority: ['R_ADD', 'R_GATE'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['黄', '床', '門', '奇数', '偶数', '手数', '増える', '順番', '先', '後'],
  hint_1: '黄色い床を踏むたび、門の状態が変わる。開くときと閉じるときがある。',
  hint_2: '黄色い床は手数も増やす。門の判定は、増やす前と後、どちらの手数を見ている？',
  hint_3: '判定は+1された後の手数を見ている。つまり偶数手で黄色を踏め。壁を殴って偶奇を合わせろ。',
  solution: ['U', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '22', level: 3, title: 'FALL',
  grid: { rows: ['#########', '#.......#', '#.#####.#', '#g......#', '#.#####.#', '#.......#', '#########'],
    legend: { g: { type: 'glass' } } },
  objects: [{ kind: 'player', x: 2, y: 5 }, { kind: 'goal', x: 1, y: 1 }],
  flags: { gravDir: 'down' },
  turn_conditions: { countBlocked: true },
  hidden_rules: [
    { id: 'R_GRAV22', name: '3回右へ進むと重力が反転する', when: 'afterMove',
      if: { op: '==', a: { v: 'streak.right' }, b: 3 },
      then: [{ do: 'flipGravity' }, { do: 'sound', name: 'low' }, { do: 'flash', text: '' }],
      note: '右へ3回 → 世界が裏返った',
      answer: ['右', '3', '回', '重力', '反転'] },
    { id: 'R_PHASE22', name: '透明な壁は奇数手のあいだだけ存在する', when: 'moveBlocked',
      if: { op: '==', a: { v: 'arg.tile' }, b: 'glass' },
      then: [{ do: 'sound', name: 'err' }],
      note: '透明な壁に阻まれた',
      answer: ['壁', '奇数', '偶数', '手目', '存在'] },
  ],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['重力', '反転', '3', '回', '壁', '奇数', '偶数', '落下', '手数', '存在'],
  hint_1: '落下は移動ではない。落ちているあいだ、MOVES は増えない。',
  hint_2: '上昇の途中で止められた。止めたものは、いつも同じ場所にあるわけではない。',
  hint_3: '透明な壁の下で1手潰せ。壁を殴れば手数だけが進み、位置は変わらない。',
  solution: ['R', 'R', 'R', 'L', 'L', 'L', 'L', 'L'],
},
{
  id: '23', level: 3, title: 'DEFINITION',
  grid: { rows: ['#########', '#..b.r..#', '#.......#', '#......b#', '#########'],
    legend: { r: RED, b: BLUEF } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { v: 'parity' }, b: 0 }],
  hidden_rules: [RED_EVEN('R_RED'), BLUE_FLIP('R_BLUE'), {
    id: 'R_GOALEVEN', name: 'ゴールも「偶数」の定義に従っている', when: 'beforeWin', if: false, then: [],
    answer: ['ゴール', '偶数', '定義', '同じ'],
  }],
  rule_priority: ['R_BLUE', 'R_RED', 'R_GOALEVEN'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ゴール', '赤', '青', '偶数', '奇数', '定義', '反転', '同じ', '床', '壁'],
  hint_1: 'ゴールの上に立った。門も抜けた。それでも駄目なら、条件は1つではない。',
  hint_2: '青い床が入れ替えたのは「壁の条件」だけだと、誰が言った？',
  hint_3: 'ゴールも同じ「偶数」を参照している。門を抜けるために反転させた定義を、もう一度戻せ。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'U', 'U'],
},
{
  id: '24', level: 3, title: 'FOUR',
  grid: { rows: ['##########', '#.....#..#', '#.....#r##', '#.....=..#', '#.....#..#', '#.....#..#', '##########'],
    legend: { '=': { type: 'grate', solid: true, boxPass: true }, r: RED } },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { id: 'bx', kind: 'box', x: 2, y: 3 },
    { kind: 'goal', x: 8, y: 1 },
  ],
  marks: [{ x: 3, y: 5, g: '4' }],
  turn_conditions: { countBlocked: true },
  hidden_rules: [
    { id: 'R_SWAP24', name: '箱を4回押すと箱とプレイヤーの位置が交換される', when: 'onPush',
      if: { op: '==', a: { objProp: ['box', 'pushed'] }, b: 4 },
      then: [{ do: 'swap', a: 'player', b: 'box' }, { do: 'sound', name: 'warp' }, { do: 'flash', text: '' }],
      note: '4回目の押し込み → 自分の居場所が変わった',
      answer: ['箱', '4', '回', '入れ替わる'] },
    RED_EVEN('R_RED'),
  ],
  rule_priority: ['R_SWAP24', 'R_RED'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '4', '回', '入れ替わる', '赤', '壁', '偶数', '奇数', '格子', '手目'],
  hint_1: 'この部屋には入口がない。だが格子は、箱だけを通す。',
  hint_2: '床に書かれた数字は装飾ではない。',
  hint_3: '4回目の押しで入れ替わる。入った先の赤い壁は、失敗した1手ぶんの手数で開く。',
  solution: ['R', 'R', 'R', 'R', 'R', 'U', 'U', 'U', 'R'],
},
];
