// LEVEL 4 -- UNDO is not a correction. It is a move, and the world counts it.
// Past selves keep walking the route you rewound away.

const UNDO_TURN = (id) => ({
  id, name: 'UNDOも1手として数えられる（手数は決して減らない）', when: 'onUndo', if: true,
  then: [{ do: 'addTurn', by: 1 }, { do: 'sound', name: 'blip' }],
  note: 'UNDOした → MOVES が減らずに増えた',
  answer: ['UNDO', '手数', '増える', '減らない'],
});

const GHOST_ON_REWIND = (id, name) => ({
  id, name, when: 'onUndo',
  if: { op: 'and', args: [{ op: '==', a: { v: 'trailLen' }, b: 1 }, { op: '>=', a: { v: 'undos' }, b: 1 }] },
  then: [{ do: 'spawnGhost', source: 'full', from: 0 }, { do: 'flash', text: '' },
    { do: 'sound', name: 'discover' }],
  note: '最初まで巻き戻した → 消したはずの自分が歩き出した',
  answer: ['UNDO', '最初', '過去', '自分', '現れる'],
});

export const L4 = [
{
  id: '25', level: 4, title: 'REWIND',
  grid: { rows: ['#########', '#.......#', '#########'] },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { v: 'turn' }, b: 10 }],
  hidden_rules: [UNDO_TURN('R_UNDOTURN')],
  laws: [{ id: 'L25', name: 'ゴールは10手目にだけ有効', answer: ['ゴール', '10', '手目'] }],
  marks: [{ x: 4, y: 1, g: '10' }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '手数', '増える', '減らない', 'ゴール', '10', '手目', '戻る', '時間', '巻き戻し'],
  hint_1: '一本道だ。歩数は選べない。……本当に？',
  hint_2: 'UNDOを押したとき、MOVES はどう動いた？',
  hint_3: 'UNDOは位置を戻すが、時間は戻さない。1歩進んで1回戻すたび、時間だけが1つ進む。',
  solution: ['R', 'Z', 'R', 'Z', 'R', 'Z', 'R', 'Z', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '26', level: 4, title: 'REVIVE',
  grid: { rows: ['#########', '#.......#', '#.......#', '#ooooooo#', '#.......#', '#ooooooo#', '#.......#', '#########'],
    legend: { o: { type: 'hole' } } },
  objects: [
    { kind: 'player', x: 3, y: 1 },
    { id: 'bx', kind: 'box', x: 3, y: 2 },
    { kind: 'goal', x: 7, y: 6 },
  ],
  hidden_rules: [
    { id: 'R_FILL26', name: '穴に落ちた箱は床になる', when: 'everyTurn',
      if: { op: '==', a: { tileAt: [{ objProp: ['box', 'x'] }, { objProp: ['box', 'y'] }] }, b: 'hole' },
      then: [{ do: 'setTile', x: { objProp: ['box', 'x'] }, y: { objProp: ['box', 'y'] }, to: 'floor' },
        { do: 'remove', ref: 'box' }, { do: 'sound', name: 'thud' }],
      note: '箱が穴へ落ちた → 穴が消えた',
      answer: ['箱', '穴', '床', '落ちる'] },
    { id: 'R_REVIVE', name: '3回UNDOすると、消えた箱だけが復活する', when: 'onUndo',
      if: { op: '==', a: { v: 'undos' }, b: 3 },
      then: [{ do: 'spawn', kind: 'box', x: 3, y: 4 }, { do: 'flash', text: '' },
        { do: 'sound', name: 'discover' }],
      note: '3回目のUNDO → 消えたはずの箱が戻ってきた',
      answer: ['UNDO', '3', '回', '箱', '復活'] },
  ],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '3', '回', '箱', '復活', '穴', '床', '落ちる', '手数', '過去'],
  hint_1: '箱は1つ。穴の帯は2本。数が足りない。',
  hint_2: 'UNDOで巻き戻る物と、巻き戻らない物がある。埋めた穴は戻ったか？',
  hint_3: '穴を埋めたあと、3手だけ歩いてから3回UNDOしろ。埋めた床は残り、箱だけが増える。',
  solution: ['D', 'R', 'L', 'R', 'Z', 'Z', 'Z', 'D', 'D', 'D', 'D', 'R', 'R', 'R', 'R'],
},
{
  id: '27', level: 4, title: 'COMPANY',
  grid: { rows: ['#########', '#.......#', '#.......#', '#######.#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 2 },
    { kind: 'switch', link: 'a', x: 5, y: 2 },
    { kind: 'door', link: 'a', x: 7, y: 2 },
    { kind: 'goal', x: 7, y: 3 },
  ],
  hidden_rules: [GHOST_ON_REWIND('R_GHOST', 'UNDOで消した経路は、過去の自分として歩き直される')],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '過去', '自分', '現れる', 'スイッチ', '扉', '最初', '同時', '経路', '時間'],
  hint_1: 'スイッチは踏み続けなければ意味がない。だが踏み続けたら扉まで歩けない。',
  hint_2: '「同時に2人いればいい」と思ったなら、正しい。',
  hint_3: 'スイッチまで歩いてから、最初まで全部UNDOしろ。お前が消した経路を、誰かが歩き直す。',
  solution: ['R', 'R', 'R', 'R', 'Z', 'Z', 'Z', 'Z', 'R', 'R', 'R', 'R', 'R', 'R', 'D'],
},
{
  id: '28', level: 4, title: 'CROWD',
  grid: { rows: ['#########', '#.......#', '#.......#', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 2 },
    { kind: 'switch', link: 'a', x: 1, y: 1 },
    { kind: 'switch', link: 'b', x: 1, y: 3 },
    { kind: 'door', link: 'a', x: 5, y: 2 },
    { kind: 'door', link: 'b', x: 6, y: 2 },
    { kind: 'goal', x: 7, y: 2 },
  ],
  hidden_rules: [{
    id: 'R_GHOST28', name: '巻き戻しきるたびに、過去の自分がもう一人増える', when: 'onUndo',
    if: { op: 'and', args: [{ op: '==', a: { v: 'trailLen' }, b: 1 }, { op: '>=', a: { v: 'undos' }, b: 1 }] },
    then: [{ do: 'spawnGhost', source: 'full', from: 0 }, { do: 'flash', text: '' },
      { do: 'sound', name: 'discover' }],
    note: '巻き戻しきった → 過去の自分がもう一人増えた',
    answer: ['UNDO', '過去', '自分', '増える', '2'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '過去', '自分', '増える', '2', 'スイッチ', '扉', '同時', '順番', '経路'],
  hint_1: '扉は2枚。スイッチも2つ。だが体は1つしかない。',
  hint_2: '過去の自分は、お前が歩いた経路の終点で立ち止まる。',
  hint_3: '過去の自分は、記録された経路の終点で止まる。スイッチの上で止まるように歩いてから巻き戻せ。それを2回。',
  solution: ['U', 'Z', 'D', 'Z', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '29', level: 4, title: 'TIME LOCK',
  grid: { rows: ['#########', '#....g..#', '#.#####.#', '#...#...#', '#########'],
    legend: { g: { type: 'glass' } } },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 1 }],
  hidden_rules: [UNDO_TURN('R_UNDOTURN29'), {
    id: 'R_PHASE29', name: '透明な壁は奇数手のあいだだけ存在する', when: 'moveBlocked',
    if: { op: '==', a: { v: 'arg.tile' }, b: 'glass' }, then: [{ do: 'sound', name: 'err' }],
    note: '透明な壁に阻まれた', answer: ['壁', '奇数', '偶数', '手目', '存在'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '手数', '増える', '壁', '奇数', '偶数', '存在', '位置', '色', '時間'],
  hint_1: '7面と同じ壁だ。だがここでは壁を殴っても手数は増えない。',
  hint_2: '手数を増やす方法は、進むこと以外にもう一つある。',
  hint_3: '1歩進んでUNDO。位置は戻り、時間だけが1つ残る。',
  solution: ['R', 'Z', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '30', level: 4, title: 'APPOINTMENT',
  grid: { rows: ['#########', '#.#######', '#.#######', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { kind: 'switch', link: 'a', x: 5, y: 3 },
    { kind: 'door', link: 'a', x: 1, y: 2 },
    { kind: 'goal', x: 1, y: 1 },
  ],
  hidden_rules: [GHOST_ON_REWIND('R_GHOST30', 'UNDOで消した経路は、過去の自分として歩き直される')],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '過去', '自分', '経路', 'スイッチ', '扉', '時刻', '同時', '待つ', '歩数'],
  hint_1: '過去の自分はスイッチの上で止まってはくれない。通り過ぎるだけだ。',
  hint_2: '通り過ぎる「その瞬間」に、お前が扉の前にいればいい。',
  hint_3: '過去の自分は1手につき1マス進む。スイッチを踏むのは経路の何歩目だ？ その歩数だけ、こちらも時間を潰せ。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'Z', 'Z', 'Z', 'Z', 'Z', 'Z',
    'R', 'L', 'R', 'L', 'U', 'U'],
},
{
  id: '31', level: 4, title: 'CAUSE',
  grid: { rows: ['#########', '#.......#', '#.....g.#', '#######.#', '#########'],
    legend: { g: { type: 'glass' } } },
  objects: [
    { kind: 'player', x: 1, y: 2 },
    { kind: 'switch', link: 'a', x: 4, y: 2 },
    { kind: 'door', link: 'a', x: 7, y: 2 },
    { kind: 'goal', x: 7, y: 3 },
  ],
  turn_conditions: { countBlocked: true },
  hidden_rules: [
    GHOST_ON_REWIND('R_GHOST31', 'UNDOで消した経路は、過去の自分として歩き直される'),
    UNDO_TURN('R_UNDOTURN31'),
    { id: 'R_PHASE31', name: '透明な壁は奇数手のあいだだけ存在する', when: 'moveBlocked',
      if: { op: '==', a: { v: 'arg.tile' }, b: 'glass' }, then: [{ do: 'sound', name: 'err' }],
      note: '透明な壁に阻まれた', answer: ['壁', '奇数', '偶数', '手目', '存在'] },
  ],
  rule_priority: ['R_UNDOTURN31', 'R_GHOST31', 'R_PHASE31'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['UNDO', '過去', '自分', '手数', '壁', '奇数', '偶数', 'スイッチ', '扉', '存在'],
  hint_1: '過去の自分に鍵を任せ、自分は時間を合わせる。やることは2つある。',
  hint_2: 'UNDOで増えた手数は、巻き戻したあとも消えない。それが位相をずらす。',
  hint_3: 'スイッチまで歩いて全部UNDO。過去の自分がスイッチに着く頃、透明な壁の前で1手潰して偶奇を合わせろ。',
  solution: ['R', 'R', 'R', 'Z', 'Z', 'Z', 'R', 'R', 'R', 'R', 'D', 'R', 'R', 'D'],
},
];
