// LEVEL 5 -- the board was never the world. The frame, the buttons and the
// note panel are all part of the machine, and all of them can be operated on.

export const L5 = [
{
  id: '32', level: 5, title: 'OUTSIDE',
  grid: { rows: [
    '#############',
    '#.......#####',
    '#.......#####',
    '#.......#####',
    '#######.#####',
    '#.....#.....#',
    '#.....#.....#',
    '#.....#.....#',
    '#############'] },
  view: { x: 0, y: 0, w: 9, h: 4 },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 11, y: 7 }],
  hidden_rules: [{
    id: 'R_FRAME', name: '盤面の外側は「見えていない」だけで、存在している', when: 'beforeMove',
    if: { op: 'and', args: [
      { op: 'not', a: { v: 'zoomed' } },
      { op: 'or', args: [{ op: '>=', a: { v: 'ty' }, b: 4 }, { op: '>=', a: { v: 'tx' }, b: 9 }] }] },
    then: [{ do: 'cancel' }, { do: 'sound', name: 'err' }],
    note: '盤面の縁で止められた → 壁ではないのに',
    answer: ['盤面', '外', '存在', '見えない'],
  }],
  available_ui_actions: ['undo', 'reset', 'zoom'],
  tokens: ['盤面', '外', '存在', '見えない', '縁', '壁', '拡大', '縮小', 'ゴール', '枠'],
  hint_1: 'この部屋に出口はない。ゴールも無い。ならば、探す場所が間違っている。',
  hint_2: '盤面の縁で止められたとき、そこに壁の絵はあったか？',
  hint_3: '二本指で盤面を縮めろ。世界はこの枠より広い。',
  solution: ['ui:zoom', 'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'D', 'D', 'D', 'D', 'R', 'R', 'R', 'R'],
},
{
  id: '33', level: 5, title: 'UPSIDE DOWN',
  grid: { rows: ['#########', '#......y#', '#.#######', '#.......#', '#######.#', '#......y#', '#########'],
    legend: { y: { type: 'yellowfloor' } } },
  objects: [{ kind: 'player', x: 1, y: 5 }, { kind: 'goal', x: 7, y: 1 }],
  flags: { gravDir: 'down' },
  rotate_step: 180,
  ui_conditions: { rotate: { op: '==', a: { v: 'tileHere' }, b: 'yellowfloor' } },
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { v: 'rot' }, b: 0 }],
  hidden_rules: [{
    id: 'R_ROT', name: '盤面は黄色い軸の上でしか回らない。回すと落ちる向きも一緒に回る',
    when: 'onUI', if: { op: '==', a: { v: 'ui.name' }, b: 'rotate' },
    then: [{ do: 'sound', name: 'low' }],
    note: '盤面が半回転した → 落下方向も操作方向も裏返った',
    answer: ['盤面', '回転', '重力', '一緒'],
  }],
  available_ui_actions: ['undo', 'reset', 'rotate'],
  tokens: ['盤面', '回転', '重力', '一緒', '軸', '黄', '操作', '逆', '落下', '正立'],
  hint_1: '登れないなら、落ちればいい。落ちる先を選べるなら。',
  hint_2: '盤面はどこでも回るわけではない。回った場所の床の色を見ろ。',
  hint_3: '軸は2枚ある。1枚目で世界を裏返して天井を歩き、2枚目――ゴールの足元――で正立に戻せ。逆さのままではクリアにならない。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'ui:rotate',
    'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'L', 'L', 'L', 'L', 'ui:rotate'],
},
{
  id: '34', level: 5, title: 'GOAL',
  grid: { rows: ['#########', '#.......#', '#######.#', '#.......#', '#.#######', '#.......#', '#########'] },
  objects: [{ kind: 'player', x: 1, y: 1 }],
  hidden_rules: [{
    id: 'R_TITLE', name: 'ステージ名そのものが、このステージのゴールである', when: 'onUI',
    if: { op: 'and', args: [
      { op: '==', a: { v: 'ui.name' }, b: 'tapTitle' },
      { op: '>=', a: { v: 'flag.titleTaps' }, b: 3 }] },
    then: [{ do: 'spawn', kind: 'goal', x: 7, y: 5 }, { do: 'flash', text: 'GOAL' },
      { do: 'sound', name: 'discover' }],
    once: true,
    note: 'ステージ名を叩いた → 名前が揺れた',
    answer: ['ステージ名', 'タップ', 'ゴール', '出現'],
  }],
  available_ui_actions: ['undo', 'reset', 'tapTitle'],
  tokens: ['ステージ名', 'タップ', 'ゴール', '出現', '盤面', '外', '文字', '3', '回', '存在'],
  hint_1: '盤面にゴールが無い。だが「ゴール」という単語なら、さっきから画面に出ている。',
  hint_2: '画面の文字は、読むためだけの物か？',
  hint_3: 'ステージ名を3回叩け。',
  solution: ['ui:tapTitle', 'ui:tapTitle', 'ui:tapTitle',
    'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'L', 'L', 'L', 'L', 'L', 'L', 'D', 'D',
    'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '35', level: 5, title: 'FOOTNOTE',
  grid: { rows: ['#########', '#.......#', '#.......#', '#.......#', '#.......#', '#.......#', '#.......#', '#########'] },
  view: { x: 0, y: 0, w: 9, h: 5 },
  objects: [{ kind: 'player', x: 1, y: 1 }, { kind: 'goal', x: 7, y: 6 }],
  hidden_rules: [{
    id: 'R_NOTE', name: 'RULE NOTE は盤面の一部を隠している', when: 'beforeMove',
    if: { op: 'and', args: [{ op: 'not', a: { v: 'flag.noteClosed' } }, { op: '>=', a: { v: 'ty' }, b: 5 }] },
    then: [{ do: 'cancel' }, { do: 'sound', name: 'err' }],
    note: '下へ進めない → 下に何かが被さっている',
    answer: ['RULE NOTE', '盤面', '隠す', '閉じる'],
  }],
  available_ui_actions: ['undo', 'reset', 'closeNote'],
  tokens: ['RULE NOTE', '盤面', '隠す', '閉じる', '下', '壁', '存在', '枠', '外', '拡大'],
  hint_1: '下に進めない。だが下にあるのは壁の絵ではない。',
  hint_2: '画面の下半分を占領しているものは何だ？',
  hint_3: 'RULE NOTE を閉じろ。あれは盤面の上に置かれている。',
  solution: ['ui:closeNote', 'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'D', 'D', 'D'],
},
{
  id: '36', level: 5, title: 'DROP',
  grid: { rows: ['#########', '#.......#', '#..oo...#', '#.......#', '#########'],
    legend: { o: { type: 'hole' } } },
  objects: [{ kind: 'player', x: 1, y: 2 }, { kind: 'goal', x: 7, y: 2 }],
  words_walkable: true,
  hidden_rules: [{
    id: 'R_DROP', name: 'UIの文字を盤面に落とすと、それは物になる', when: 'onUI',
    if: { op: '==', a: { v: 'ui.name' }, b: 'dropUI' },
    then: [{ do: 'setTile', x: { v: 'ui.x' }, y: { v: 'ui.y' }, to: 'floor' },
      { do: 'flash', text: '' }, { do: 'sound', name: 'discover' }],
    note: 'ボタンを盤面へ落とした → 落ちた場所が変わった',
    answer: ['UI', '文字', '盤面', '物', '落とす'],
  }],
  available_ui_actions: ['undo', 'reset', 'dropUI'],
  tokens: ['UI', '文字', '盤面', '物', '落とす', '穴', '床', 'ボタン', '2', '存在'],
  hint_1: '穴を埋める箱が無い。盤面の上には、な。',
  hint_2: '画面には四角い物が並んでいる。RESET、UNDO。あれは何でできている？',
  hint_3: '穴は2マスある。ボタンも2つある。',
  solution: ['ui:dropUI:RESET,3,2', 'ui:dropUI:UNDO,4,2', 'R', 'R', 'R', 'R', 'R', 'R'],
},
];
