// LEVEL 6-8 -- the UI is made of matter, one stage reaches into another, and
// the sentences lying on the floor are the engine's own source code.

export const L6 = [
{
  id: '37', level: 6, title: 'DOOR 4',
  grid: { rows: ['#########', '#.......#', '#######.#', '#.......#', '#.#######', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { id: 'door1', kind: 'door', x: 1, y: 4, label: '4', slot: 'pre',
      openIf: { op: '==', a: { label: '#door1' }, b: '14' } },
    { kind: 'goal', x: 1, y: 5 },
  ],
  hidden_rules: [{
    id: 'R_DIGIT', name: 'UIに表示された数字は、部品として取り外せる', when: 'onUI',
    if: { op: '==', a: { v: 'ui.name' }, b: 'dropChar' },
    then: [{ do: 'sound', name: 'discover' }, { do: 'flash', text: '' }],
    note: '画面の数字を引き剥がした → 扉の名前が変わった',
    answer: ['UI', '数字', '部品', '扉', '名前'],
  }],
  available_ui_actions: ['undo', 'reset', 'dropChar'],
  tokens: ['UI', '数字', '部品', '扉', '名前', 'MOVES', '14', '4', '一致', '外す'],
  hint_1: 'この扉には名前が書いてある。DOOR 4。',
  hint_2: '画面のどこかに、まだ使っていない数字が表示されている。MOVES だ。',
  hint_3: 'MOVES が 14 のとき、その "1" を掴んで扉の空欄へ落とせ。DOOR 14 になる。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'L', 'L', 'L', 'L', 'L', 'L',
    'ui:dropChar:1,#door1', 'D', 'D'],
},
{
  id: '38', level: 6, title: 'RE|SET',
  grid: { rows: ['#########', '#.......#', '#.......#', '#.....#.#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { id: 'door2', kind: 'door', x: 7, y: 2, label: 'SET',
      openIf: { op: '==', a: { textAt: [6, 1] }, b: 'SET' } },
    { kind: 'goal', x: 7, y: 3 },
  ],
  words_walkable: true,
  marks: [{ x: 6, y: 1, g: '_' }],
  hidden_rules: [{
    id: 'R_SPLIT', name: 'UIの単語は切り離せる。RESET から SET だけを取り出せる', when: 'onUI',
    if: { op: '==', a: { v: 'ui.name' }, b: 'splitWord' },
    then: [{ do: 'sound', name: 'discover' }, { do: 'flash', text: '' }],
    note: '単語が二つに割れた',
    answer: ['UI', '単語', '切る', 'SET', '取り出す'],
  }],
  available_ui_actions: ['undo', 'reset', 'dropUI', 'splitWord', 'wordDrag'],
  tokens: ['UI', '単語', '切る', 'SET', '取り出す', 'RESET', '扉', '文字', '落とす', '嵌める'],
  hint_1: '扉には SET と書かれている。盤面に SET は無い。画面には？',
  hint_2: 'RESET という単語の中に、探している3文字が入っている。',
  hint_3: 'RESET を盤面に落とし、RE と SET に割って、SET だけを窪みへ運べ。',
  solution: ['ui:dropUI:RESET,2,1', 'ui:splitWord:#ui_RESET,2,3,1', 'ui:wordDrag:#ui_SET,6,1',
    'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D'],
},
{
  id: '39', level: 6, title: 'STAGE 39',
  grid: { rows: ['#########', '#.......#', '#.....#.#', '#.......#', '#########'] },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { id: 'door3', kind: 'door', x: 6, y: 1, label: '3', slot: 'post',
      openIf: { op: '==', a: { label: '#door3' }, b: '39' } },
    { kind: 'goal', x: 7, y: 1 },
  ],
  hidden_rules: [{
    id: 'R_STAGENUM', name: 'ステージ番号も、ただの数字の並びである', when: 'onUI',
    if: { op: '==', a: { v: 'ui.name' }, b: 'dropChar' },
    then: [{ do: 'sound', name: 'discover' }],
    note: 'ステージ番号から数字が剥がれた',
    answer: ['ステージ', '番号', '数字', '扉', '一致'],
  }],
  available_ui_actions: ['undo', 'reset', 'dropChar'],
  tokens: ['ステージ', '番号', '数字', '扉', '一致', 'MOVES', '39', '9', '外す', '名前'],
  hint_1: 'DOOR 3。あと一文字足りない。',
  hint_2: 'MOVES から取れるとは限らない。画面の左上には何が書いてある？',
  hint_3: 'STAGE 39 の "9" を扉へ。扉がこのステージそのものになる。',
  solution: ['ui:dropChar:9,#door3', 'R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '40', level: 8, title: 'ELSEWHERE',
  grid: { rows: ['#########', '#...#...#', '#...#...#', '#...#...#', '#########'] },
  objects: [{ kind: 'player', x: 1, y: 2 }, { kind: 'goal', x: 7, y: 2 }],
  marks: [{ x: 4, y: 1, g: '1' }, { x: 4, y: 3, g: '2' }],
  hidden_rules: [
    { id: 'R_MARK40', name: 'このステージに来たこと自体が、別のステージを書き換える', when: 'start', if: true,
      then: [{ do: 'setGlobal', key: 's40_seen', value: true }],
      note: 'この部屋に入った → どこか遠くで物音がした',
      answer: ['ステージ', '影響', '別', '往復'] },
    { id: 'R_OPEN40', name: 'ステージ12の台座に箱が載ると、ここの壁が消える', when: 'start',
      if: { global: 's12_box_placed' },
      then: [{ do: 'setTile', x: 4, y: 2, to: 'floor' }, { do: 'flash', text: '' },
        { do: 'sound', name: 'discover' }],
      answer: ['12', '箱', '台座', '壁', '消える'] },
  ],
  cross_stage_variables: { read: ['s12_box_placed'], write: ['s40_seen'] },
  test_globals: { s12_box_placed: true },
  probe: [],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ステージ', '12', '箱', '台座', '壁', '消える', '別', '影響', '往復', '番号'],
  hint_1: 'この壁を消す手段は、この部屋の中には無い。ひとつも。',
  hint_2: '壁に刻まれた数字を読め。1と2。並べれば12。',
  hint_3: 'ステージ12へ戻れ。以前は無かった箱がある。それを台座へ載せてから、ここへ帰ってこい。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R'],
},
{
  id: '41', level: 6, title: 'WALL IS SOLID',
  grid: { rows: ['#########', '#...#...#', '#...#...#', '#...#...#', '#...#...#', '#...#...#', '#########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { PLAYER: ['YOU'], GOAL: ['CLEAR'], BOX: ['PUSH'] } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'word', text: 'WALL', x: 1, y: 4 },
    { kind: 'word', text: 'IS', x: 2, y: 4 },
    { kind: 'word', text: 'SOLID', x: 3, y: 4 },
    { kind: 'goal', x: 7, y: 3 },
  ],
  hidden_rules: [{
    id: 'R_SENT', name: '盤面の文章はこの世界の設定そのものである', when: 'onPush', if: true,
    then: [{ do: 'sound', name: 'low' }],
    note: '文章の一部を押した → 世界の手応えが変わった',
    answer: ['文章', '世界', '設定', '壁', '押す'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['文章', '世界', '設定', '壁', '押す', 'SOLID', '外す', '通過', '単語', '意味'],
  hint_1: '床に落ちている文章は、説明文ではない。',
  hint_2: 'WALL IS SOLID。この一行が正しいあいだ、壁は硬い。',
  hint_3: 'SOLID を行から押し出せ。文が壊れれば、壁は硬さを失う。',
  solution: ['R', 'R', 'D', 'D', 'D', 'R', 'R', 'R', 'R', 'U'],
},
{
  id: '42', level: 6, title: 'DO NOT TOUCH',
  grid: { rows: ['#########', '#.....#.#', '#.....#.#', '#.....#.#', '#.....#.#', '#.....#.#', '#########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { PLAYER: ['YOU'], BOX: ['PUSH'] } },
  objects: [
    { kind: 'player', x: 5, y: 1 },
    { kind: 'word', text: 'WALL', x: 1, y: 2 },
    { kind: 'word', text: 'IS', x: 2, y: 2 },
    { kind: 'word', text: 'SOLID', x: 3, y: 2 },
    { kind: 'word', text: 'GOAL', x: 1, y: 4 },
    { kind: 'word', text: '=', x: 2, y: 4 },
    { kind: 'word', text: 'CLEAR', x: 3, y: 4 },
    { kind: 'goal', x: 7, y: 3 },
  ],
  hidden_rules: [{
    id: 'R_SENT42', name: 'GOAL = CLEAR を壊すと、ゴールしてもクリアにならない', when: 'onPush', if: true,
    then: [{ do: 'sound', name: 'low' }],
    note: '文章を動かした → 何かの意味が消えた',
    answer: ['ゴール', 'CLEAR', '壊す', 'クリア', 'できない'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ゴール', 'CLEAR', '壊す', '文章', '壁', 'SOLID', '押す', '方向', '二行', '意味'],
  hint_1: '壁を抜けたいなら上の行を壊せばいい。だが行は二つある。',
  hint_2: 'SOLID を下へ押し込んだら、その下には何がある？',
  hint_3: '押す向きを選べ。CLEAR を巻き込まずに SOLID だけを行から外す道が、ひとつだけある。',
  solution: ['L', 'L', 'D', 'R', 'R', 'R', 'R', 'D'],
},
{
  id: '43', level: 7, title: 'THIS RULE IS FALSE',
  grid: { rows: ['##########', '#.B..B.B.#', '#........#', '#........#', '#........#',
    '#........#', '##########'],
    legend: { B: { type: 'bluewall' } } },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { WALL: ['SOLID'], PLAYER: ['YOU'], GOAL: ['CLEAR'] } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'word', text: 'THIS', x: 1, y: 3 },
    { kind: 'word', text: 'RULE', x: 2, y: 3 },
    { kind: 'word', text: 'IS', x: 3, y: 3 },
    { kind: 'word', text: 'FALSE', x: 4, y: 3 },
    { kind: 'word', text: 'BLUE', x: 1, y: 5 },
    { kind: 'word', text: 'IS', x: 2, y: 5 },
    { kind: 'word', text: 'SOLID', x: 3, y: 5 },
    { kind: 'goal', x: 8, y: 1 },
  ],
  hidden_rules: [
    { id: 'R_PARADOX', name: '「この規則は偽である」の真偽は1手ごとに入れ替わり、直後の一文を殺す',
      when: 'moveBlocked', if: { op: '==', a: { v: 'arg.tile' }, b: 'bluewall' },
      then: [{ do: 'addFlag', flag: 'rejects', by: 1 }, { do: 'sound', name: 'err' },
        { do: 'flash', text: 'SEEN' }],
      note: '青い門に弾かれた → 門は弾いた回数を覚えている',
      answer: ['規則', '偽', '1', '手', '交互'] },
    { id: 'R_CAUGHT', name: '青い門は2度目の誤りを許さない', when: 'afterMove',
      if: { op: '>=', a: { v: 'flag.rejects' }, b: 2 },
      then: [{ do: 'fail' }, { do: 'sound', name: 'dead' }],
      answer: ['門', '2', '回', '失敗', '終わり'] },
  ],
  rule_priority: ['R_PARADOX', 'R_CAUGHT'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['規則', '偽', '交互', '1', '手', '門', '2', '回', '評価', '順番'],
  hint_1: '門は3つ。だが試せる回数は限られている。まず、試さずに済む壁を殴れ。',
  hint_2: '自分を否定する文が上の行にある。真なら偽、偽なら真――つまり1手ごとに裏返る。',
  hint_3: '門が開くのは奇数手のあいだだけだ。門の手前で普通の壁を殴って手数を合わせろ。門に弾かれるのは2回まで。',
  solution: ['U', 'R', 'R', 'R', 'U', 'R', 'R', 'R', 'R'],
},
{
  id: '44', level: 7, title: 'IGNORE',
  grid: { rows: ['##########', '#........#', '#........#', '#........#', '#........#', '#........#', '#.....##.#', '##########'],
    legend: {} },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { PLAYER: ['YOU'], GOAL: ['CLEAR'], BOX: ['PUSH'] } },
  objects: [
    { kind: 'player', x: 1, y: 2 },
    { id: 'slider', kind: 'box', x: 2, y: 1, slide: true },
    { kind: 'switch', link: 'a', x: 6, y: 1 },
    { kind: 'word', text: 'IGNORE', x: 1, y: 3 },
    { kind: 'word', text: 'NEXT', x: 2, y: 3 },
    { kind: 'word', text: 'RULE', x: 3, y: 3 },
    { kind: 'word', text: 'WALL', x: 1, y: 5 },
    { kind: 'word', text: 'IS', x: 2, y: 5 },
    { kind: 'word', text: 'SOLID', x: 3, y: 5 },
    { kind: 'door', link: 'a', x: 8, y: 5 },
    { kind: 'goal', x: 8, y: 6 },
  ],
  hidden_rules: [{
    id: 'R_IGNORE', name: 'IGNORE NEXT RULE は、読み順で次に来る一文を無効化する', when: 'onPush', if: true,
    then: [{ do: 'sound', name: 'low' }],
    note: '無効化の矢印が向く先は、読み順で決まっているらしい',
    answer: ['IGNORE', '次', '無効', '読み順', '上から'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['IGNORE', '次', '無効', '読み順', '上から', '壁', 'SOLID', '箱', '止まる', '文章'],
  hint_1: '箱が止まらない。止めるはずの壁が、硬くない。',
  hint_2: 'WALL IS SOLID は書いてある。書いてあるのに効いていない。何かがそれを打ち消している。',
  hint_3: 'IGNORE NEXT RULE を壊せ。単語をひとつ行から外すだけでいい。',
  solution: ['D', 'U', 'U', 'R', 'D', 'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D', 'D', 'D'],
},
{
  id: '45', level: 7, title: 'ORDER OF LAW',
  grid: { rows: ['###########', '#.......#.#', '#.......#.#', '#.......#.#', '#.......#.#', '#.......#.#', '###########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { PLAYER: ['YOU'], GOAL: ['CLEAR'] } },
  objects: [
    { kind: 'player', x: 1, y: 5 },
    { kind: 'word', text: 'WALL', x: 1, y: 1 },
    { kind: 'word', text: 'IS', x: 2, y: 1 },
    { kind: 'word', text: 'SOLID', x: 3, y: 1 },
    { kind: 'word', text: 'IGNORE', x: 1, y: 3 },
    { kind: 'word', text: 'NEXT', x: 2, y: 3 },
    { kind: 'word', text: 'RULE', x: 3, y: 3 },
    { kind: 'word', text: 'IGNORE', x: 5, y: 3 },
    { kind: 'word', text: 'PREVIOUS', x: 6, y: 3 },
    { kind: 'word', text: 'RULE', x: 7, y: 3 },
    { kind: 'goal', x: 9, y: 3 },
  ],
  hidden_rules: [{
    id: 'R_ORDER', name: '文章は上から、同じ行なら左から評価される', when: 'onPush', if: true,
    then: [{ do: 'sound', name: 'low' }],
    note: '二つの命令が互いを打ち消し合っている',
    answer: ['読み順', '上から', '左から', '先', '勝つ'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['読み順', '上から', '左から', '先', '勝つ', 'IGNORE', '次', '前', '無効', '壁'],
  hint_1: 'IGNORE NEXT と IGNORE PREVIOUS。どちらが有効なのかは、書かれた位置で決まる。',
  hint_2: '先に読まれた命令が、後の命令を殺している。殺された命令は何もしない。',
  hint_3: '先に読まれる側の命令を1単語壊せ。生き残った命令が、上の行へ牙を剥く。',
  solution: ['R', 'U', 'U', 'D', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'U'],
},
{
  id: '46', level: 7, title: 'HALF TRUE',
  grid: { rows: ['##########', '#........#', '########.#', '#........#', '#.########',
    '#........#', '#........#', '#........#', '##########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { WALL: ['SOLID'], PLAYER: ['YOU'] } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'word', text: 'THIS', x: 1, y: 6 },
    { kind: 'word', text: 'RULE', x: 2, y: 6 },
    { kind: 'word', text: 'IS', x: 3, y: 6 },
    { kind: 'word', text: 'FALSE', x: 4, y: 6 },
    { kind: 'word', text: 'GOAL', x: 1, y: 7 },
    { kind: 'word', text: '=', x: 2, y: 7 },
    { kind: 'word', text: 'CLEAR', x: 3, y: 7 },
    { kind: 'goal', x: 8, y: 5 },
  ],
  turn_conditions: { countBlocked: true },
  hidden_rules: [{
    id: 'R_HALF', name: '矛盾文の直後の一行は、1手ごとに有効と無効を繰り返す', when: 'beforeWin', if: false, then: [],
    answer: ['矛盾', '次', '1', '手', '交互'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['矛盾', '次', '交互', '1', '手', 'ゴール', 'CLEAR', '無効', '読み順', '偶数'],
  hint_1: 'ゴールの上に立った。何も起きない。もう一度立っても同じ。',
  hint_2: '矛盾文の真下にあるのは GOAL = CLEAR だ。43面で門に起きたことを思い出せ。',
  hint_3: 'ゴールの上で1手潰すか、あるいは矛盾文そのものを1単語ぶん壊せ。どちらでも通る。',
  solution: ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'D', 'D',
    'L', 'L', 'L', 'L', 'L', 'L', 'L', 'D', 'D',
    'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R'],
},
];
