// The stages that are not on the map: the one made by fusing two numbers,
// the one with nothing in it, and the ones behind the title.

export const L7 = [
{
  id: '47', level: 8, title: 'FUSION', hidden: true,
  madeOf: ['24', '7'],
  grid: { rows: ['##########', '#.....#..#', '#.....#g##', '#.....=..#', '#.....#..#', '#.....#..#', '##########'],
    legend: { '=': { type: 'grate', solid: true, boxPass: true }, g: { type: 'glass' } } },
  objects: [
    { kind: 'player', x: 1, y: 3 },
    { id: 'bx', kind: 'box', x: 2, y: 3 },
    { kind: 'goal', x: 7, y: 2 },
  ],
  turn_conditions: { startTurn: 40, countBlocked: true },
  win_conditions: [{ at: ['player', 'goal'] }, { op: '==', a: { v: 'turn' }, b: 47 }],
  marks: [{ x: 3, y: 5, g: '4' }, { x: 4, y: 5, g: '7' }],
  hidden_rules: [
    { id: 'R_SWAP47', name: '箱を4回押すと箱とプレイヤーの位置が交換される', when: 'onPush',
      if: { op: '==', a: { objProp: ['box', 'pushed'] }, b: 4 },
      then: [{ do: 'swap', a: 'player', b: 'box' }, { do: 'sound', name: 'warp' }],
      note: '4回目の押し込み → 位置が交換された', answer: ['箱', '4', '回', '入れ替わる'] },
    { id: 'R_PHASE47', name: '透明な壁は奇数手のあいだだけ存在する', when: 'moveBlocked',
      if: { op: '==', a: { v: 'arg.tile' }, b: 'glass' }, then: [{ do: 'sound', name: 'err' }],
      note: '透明な壁に阻まれた', answer: ['壁', '奇数', '偶数', '手目', '存在'] },
    { id: 'R_47', name: 'このステージは40から始まり、47で終わる', when: 'start', if: true, then: [],
      answer: ['40', '47', '手目', 'ゴール', '番号'] },
  ],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['箱', '4', '回', '入れ替わる', '壁', '奇数', '偶数', '40', '47', '手目'],
  hint_1: 'MOVES は 0 から始まっていない。',
  hint_2: 'このステージは24と7でできている。だから法則も2つとも生きている。',
  hint_3: '40から始まって47で終わる。つまり許された手数はちょうど7。1手も無駄にできない――弾かれた1手を除いて。',
  solution: ['R', 'R', 'R', 'R', 'R', 'U', 'U'],
},
{
  id: 'FINAL', level: 9, title: 'THERE IS NO PUZZLE',
  grid: { rows: ['#########', '#.......#', '#.......#', '#.......#', '#.......#', '#.......#', '#########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: {},
  existence_kinds: ['PLAYER', 'GOAL'],
  spawns: { PLAYER: { x: 6, y: 2 }, GOAL: { x: 6, y: 4 } },
  objects: [],
  banner: 'THERE IS NO PUZZLE.',
  ui_words: ['PLAYER', 'GOAL', 'EXISTS', '=', 'IS', 'WALL', 'SOLID', 'CLEAR'],
  win_conditions: [{ has: 'PLAYER EXISTS' }, { has: 'GOAL EXISTS' }, { has: 'PLAYER = GOAL' }],
  hidden_rules: [{
    id: 'R_FINAL', name: 'このステージには規則が無い。だから自分で書く', when: 'onUI', if: true,
    then: [{ do: 'sound', name: 'blip' }],
    note: '空白に単語を置いた → 世界が少しだけ形を持った',
    answer: ['規則', '無い', '自分', '書く', '存在'],
  }],
  available_ui_actions: ['undo', 'reset', 'zoom', 'rotate', 'dropUI', 'wordDrag', 'splitWord',
    'dropChar', 'closeNote', 'tapTitle'],
  tokens: ['規則', '無い', '自分', '書く', '存在', 'プレイヤー', 'ゴール', '同じ', '単語', '世界'],
  hint_1: '盤面には何も無い。だが画面には、まだ大量の材料が残っている。',
  hint_2: 'これまでの50面で、単語を並べれば世界が変わることを見てきたはずだ。',
  hint_3: 'PLAYER EXISTS。GOAL EXISTS。そして PLAYER = GOAL。3つ書ければ終わる。',
  solution: ['ui:dropUI:PLAYER,1,1', 'ui:dropUI:EXISTS,2,1',
    'ui:dropUI:GOAL,1,3', 'ui:dropUI:EXISTS,2,3',
    'ui:dropUI:PLAYER,1,5', 'ui:dropUI:=,2,5', 'ui:dropUI:GOAL,3,5'],
},
{
  id: 'NULL-1', level: 10, title: 'TWO LIES', hidden: true, nullStage: true,
  grid: { rows: ['##########', '#.B..B.B.#', '#........#', '#........#', '#........#',
    '#........#', '#........#', '##########', '#........#', '##########'],
    legend: { B: { type: 'bluewall' } } },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { WALL: ['SOLID'], PLAYER: ['YOU'], GOAL: ['CLEAR'] } },
  objects: [
    { kind: 'player', x: 1, y: 1 },
    { kind: 'word', text: 'THIS', x: 2, y: 3 },
    { kind: 'word', text: 'RULE', x: 3, y: 3 },
    { kind: 'word', text: 'IS', x: 4, y: 3 },
    { kind: 'word', text: 'FALSE', x: 5, y: 3 },
    { kind: 'word', text: 'THIS', x: 2, y: 5 },
    { kind: 'word', text: 'RULE', x: 3, y: 5 },
    { kind: 'word', text: 'IS', x: 4, y: 5 },
    { kind: 'word', text: 'FALSE', x: 5, y: 5 },
    { kind: 'word', text: 'BLUE', x: 2, y: 8 },
    { kind: 'word', text: 'IS', x: 3, y: 8 },
    { kind: 'word', text: 'SOLID', x: 4, y: 8 },
    { kind: 'goal', x: 8, y: 1 },
  ],
  hidden_rules: [
    { id: 'R_TWOLIES', name: '矛盾文が2つあると、互いを打ち消して門は常に閉じたままになる',
      when: 'moveBlocked', if: { op: '==', a: { v: 'arg.tile' }, b: 'bluewall' },
      then: [{ do: 'addFlag', flag: 'rejects', by: 1 }, { do: 'sound', name: 'err' },
        { do: 'flash', text: 'SEEN' }],
      note: '青い門に弾かれた → 門は弾いた回数を覚えている',
      answer: ['矛盾', '2', '打ち消す', '常に', '硬い'] },
    { id: 'R_CAUGHT1', name: '青い門は2度目の誤りを許さない', when: 'afterMove',
      if: { op: '>=', a: { v: 'flag.rejects' }, b: 2 },
      then: [{ do: 'fail' }, { do: 'sound', name: 'dead' }],
      answer: ['門', '2', '回', '失敗', '終わり'] },
  ],
  rule_priority: ['R_TWOLIES', 'R_CAUGHT1'],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['矛盾', '2', '打ち消す', '常に', '硬い', '読み順', '次', '無効', '門', '交互'],
  hint_1: '43面では門が1手ごとに揺らいだ。ここでは揺らがない。増えたものは何だ。',
  hint_2: '一番下の行には手が届かない。触れるのは嘘つき2人だけだ。',
  hint_3: '2つ目の矛盾文を「文章として成立しない」形に壊せ。端の単語では駄目だ、真ん中を抜け。',
  solution: ['D', 'D', 'D', 'D', 'D', 'R', 'R', 'U',
    'R', 'R', 'R', 'U', 'U', 'U', 'L', 'L', 'L', 'L', 'L', 'U',
    'U', 'R', 'R', 'R', 'U', 'R', 'R', 'R', 'R'],
},
{
  id: 'NULL-2', level: 10, title: 'MAKE IT EXIST', hidden: true, nullStage: true,
  grid: { rows: ['#########', '#.....#.#', '#.....#.#', '#.....#.#', '#.....#.#', '#########'] },
  use_sentences: true,
  words_pushable: true,
  semantics_defaults: { props: { PLAYER: ['YOU'], GOAL: ['CLEAR'] } },
  existence_kinds: ['GOAL'],
  spawns: { GOAL: { x: 7, y: 3 } },
  objects: [
    { kind: 'player', x: 1, y: 4 },
    { kind: 'word', text: 'GOAL', x: 1, y: 1 },
    { kind: 'word', text: 'EXISTS', x: 2, y: 2 },
    { kind: 'word', text: 'WALL', x: 3, y: 3 },
    { kind: 'word', text: 'IS', x: 4, y: 3 },
    { kind: 'word', text: 'SOLID', x: 5, y: 3 },
  ],
  hidden_rules: [{
    id: 'R_EXIST', name: '「GOAL EXISTS」と書けば、ゴールは存在するようになる', when: 'onPush', if: true,
    then: [{ do: 'sound', name: 'low' }],
    note: '単語を動かした → 無かったものが生まれた',
    answer: ['ゴール', '存在', '書く', '生まれる', '単語'],
  }],
  available_ui_actions: ['undo', 'reset'],
  tokens: ['ゴール', '存在', '書く', '生まれる', '単語', '壁', 'SOLID', '押す', '向き', '2'],
  hint_1: 'ゴールが無い。壁も抜けない。やることは2つある。',
  hint_2: '離れた2単語をくっつけろ。押せる向きは限られている。',
  hint_3: 'EXISTS を GOAL の隣まで押し上げてから、SOLID を行から落とせ。順番を逆にすると届かなくなる。',
  solution: ['R', 'U', 'U', 'R', 'R', 'R', 'D', 'R', 'R'],
},
{
  id: 'NULL-3', level: 10, title: 'ZERO', hidden: true, nullStage: true,
  grid: { rows: [
    '#########', '#.......#', '#.......#', '#.......#', '#.......#',
    '#.......#', '#.......#', '#.......#', '#########'] },
  view: { x: 0, y: 0, w: 3, h: 3 },
  use_sentences: true,
  semantics_defaults: {},
  existence_kinds: ['PLAYER', 'GOAL'],
  spawns: { PLAYER: { x: 1, y: 1 }, GOAL: { x: 1, y: 1 } },
  objects: [],
  banner: '1',
  ui_words: ['GOAL', 'EXISTS', 'PLAYER', '=', 'IS', 'WALL', 'SOLID'],
  win_conditions: [{ has: 'PLAYER EXISTS' }, { has: 'GOAL EXISTS' }, { at: ['player', 'goal'] }],
  hidden_rules: [{
    id: 'R_ZERO', name: '1マスしかない世界でも、世界の外には余白がある', when: 'onUI',
    if: { op: 'and', args: [{ op: 'not', a: { v: 'zoomed' } },
      { op: '==', a: { v: 'ui.name' }, b: 'dropUI' },
      { op: 'or', args: [{ op: '>=', a: { v: 'ui.x' }, b: 3 }, { op: '>=', a: { v: 'ui.y' }, b: 3 }] }] },
    then: [{ do: 'cancel' }, { do: 'sound', name: 'err' }],
    note: '3マスの世界の外には、まだ何も書けない',
    answer: ['世界', '外', '余白', '存在', '拡大'],
  }],
  available_ui_actions: ['undo', 'reset', 'zoom', 'dropUI', 'wordDrag'],
  tokens: ['世界', '外', '余白', '存在', '拡大', 'ゴール', '単語', '書く', '1', '0'],
  hint_1: 'プレイヤーもゴールも無い。動く場所も、書く場所も無い。ならば場所を増やせ。',
  hint_2: '32面でやったことを、もう一度。ただし今度は歩くためではない。',
  hint_3: '余白に PLAYER EXISTS と GOAL EXISTS を両方書け。二人は同じ一マスに生まれる。',
  solution: ['ui:zoom', 'ui:dropUI:PLAYER,4,4', 'ui:dropUI:EXISTS,5,4',
    'ui:dropUI:GOAL,4,6', 'ui:dropUI:EXISTS,5,6'],
},
];
